---
title: 'Project 2'
author: ''
date: '`r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    theme: yeti
    highlight: textmate
    toc: true
    toc_float: false
    toc_depth: 4
    code_folding: hide
---

```{r setup_chunk, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = "")
```


#Setup


Packages:

```{r}
library(dplyr)
library(XML)
library(stringr)
library(blscrapeR)
library(openxlsx)
library(tidyr)

```


Initial Loading of Powerball dataset:

```{r}
#loading winning numbers dataset
winningnumbers <- read.csv("https://data.ny.gov/api/views/d6yy-54nr/rows.csv?accessType=DOWNLOAD")

winningnumbers

#loading jackpot vals
url <- "http://www.lottofactor.com/script/jackpot_history/draw_date/101"

jackpot_vals <- readHTMLTable(url)[[18]] %>% 
  mutate_all(funs(str_replace(., pattern = "Â", replacement = ""))) %>% 
  mutate_all(funs(str_trim(., "left")))

#renaming the variables
jackpot_vals <- rename(jackpot_vals, drawdate = `Â Draw Date`)

jackpot_vals <- rename(jackpot_vals, Change = `Â Change`)

jackpot_vals <- rename(jackpot_vals, Jackpot.Amount = `Â Jackpot Amount`)

# adjusting inflation
inflation_adj <- inflation_adjust(2019)

# editing winning numbers
winningnumbers <- winningnumbers %>% separate(Winning.Numbers, into = c("white1", "white2", "white3", "white4", "white5", "powerball"), sep = " ")

winningnumbers <- rename(winningnumbers, drawdate = Draw.Date)


#editing jackpot vals to begin to create new dataset
jackpot_vals <- jackpot_vals %>% separate("drawdate", into = c("drawday", "drawdate"), sep = " ")

jackpot_vals$Change = gsub("\\$", "", jackpot_vals$Change)
jackpot_vals$Change = gsub("Million", "", jackpot_vals$Change)

jackpot_vals$Jackpot.Amount = gsub("\\$", "", jackpot_vals$Jackpot.Amount)
jackpot_vals$Jackpot.Amount = gsub("Million", "", jackpot_vals$Jackpot.Amount)
jackpot_vals$Jackpot.Amount <- as.numeric(jackpot_vals$Jackpot.Amount)

jackpot_vals <- rename(jackpot_vals, jackpot_value = Jackpot.Amount)

winningnumbers

jackpot_vals

```

Creating dataset "powerball"

```{r}
jackpot_vals$drawdate <- as.Date(jackpot_vals$drawdate, "%m/%d/%Y")
jackpot_vals

winningnumbers$drawdate <- as.Date(winningnumbers$drawdate, "%m/%d/%Y")
winningnumbers

powerball <- left_join(jackpot_vals, winningnumbers, by = "drawdate")
powerball
```




Initial Loading of Population Data

```{r}
```

